# Generated by Django 4.2.7 on 2024-02-21 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('add', models.CharField(max_length=100)),
                ('con', models.BigIntegerField()),
                ('lic', models.ImageField(upload_to='')),
                ('psw', models.CharField(max_length=20)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.CharField(max_length=20, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutJournals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, null=True)),
                ('duration', models.CharField(max_length=20, null=True)),
                ('workouts', models.CharField(max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phwApp.registration')),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=20)),
                ('file', models.FileField(upload_to='')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phwApp.expert')),
            ],
        ),
        migrations.CreateModel(
            name='Tips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=200)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phwApp.expert')),
            ],
        ),
        migrations.CreateModel(
            name='SleepJournals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, null=True)),
                ('duration', models.CharField(max_length=20, null=True)),
                ('desc', models.CharField(max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phwApp.registration')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, null=True)),
                ('height', models.CharField(max_length=20, null=True)),
                ('weight', models.CharField(max_length=20, null=True)),
                ('healthstat', models.CharField(max_length=200, null=True)),
                ('bmi', models.CharField(max_length=200, null=True)),
                ('bmr', models.CharField(max_length=200, null=True)),
                ('goal', models.CharField(max_length=200, null=True)),
                ('activeStatus', models.CharField(max_length=200, null=True)),
                ('reqCal', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phwApp.registration')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalJournals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, null=True)),
                ('desc', models.CharField(max_length=20, null=True)),
                ('report', models.FileField(upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phwApp.registration')),
            ],
        ),
        migrations.CreateModel(
            name='FoodJournals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, null=True)),
                ('calorieIntake', models.CharField(max_length=20, null=True)),
                ('time', models.CharField(max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phwApp.registration')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sendby', models.CharField(max_length=40)),
                ('date', models.DateField(auto_now_add=True)),
                ('message', models.CharField(max_length=400)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phwApp.expert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phwApp.registration')),
            ],
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=200)),
                ('expert', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='phwApp.expert')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='phwApp.registration')),
            ],
        ),
    ]
