# Generated by Django 4.2.7 on 2024-02-21 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phwApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='status',
        ),
    ]
