# Generated by Django 4.2.7 on 2024-02-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phwApp', '0002_remove_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(default='In Progress', max_length=500),
        ),
    ]
