# Generated by Django 4.2.7 on 2024-02-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phwApp', '0004_remove_foodjournals_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodjournals',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sleepjournals',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workoutjournals',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
