# Generated by Django 4.2.7 on 2024-02-23 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phwApp', '0005_foodjournals_status_sleepjournals_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('comment', models.CharField(max_length=200)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phwApp.blogs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phwApp.registration')),
            ],
        ),
    ]
