# Generated by Django 4.2.7 on 2024-02-23 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phwApp', '0006_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='expert',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='phwApp.expert'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='phwApp.registration'),
        ),
    ]
