# Generated by Django 4.2.7 on 2024-03-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phwApp', '0008_booking_prescription_payment_doctor_booking_docid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='qualification',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
