# Generated by Django 4.2.7 on 2024-04-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phwApp', '0010_remove_booking_token_booking_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='token',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(default='Booked', max_length=100),
        ),
    ]
